GET http://localhost:8080/api/greeting/hello

###

GET http://localhost:8080/api/greeting/json
Accept: application/json

###

GET http://localhost:8080/api/greeting/person
Accept: application/json

###